# Generated by Django 5.0 on 2023-12-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
